name: Weekly Tests

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0/2 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup-project

      - name: Lint and Unit Test
        uses: ./.github/actions/lint-and-unit-test

      - name: Run e2e tests
        run: npm run test:e2e
        env:
          E2E_BASE_URL: 'https://frontend-bootstrap-ten.vercel.app/'

      - name: Send test results
        uses: ./.github/actions/notify-webhook
        if: ${{ job.status == 'success' }}
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          message: 'E2E tests succeeded'

      - name: Send test results
        uses: ./.github/actions/notify-webhook
        if: ${{ failure() }}
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          message: 'E2E tests failed'
