name: Deploy - AWS

on:
  workflow_call:

jobs:
  deploy-aws:
    environment:
      name: 'Production'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure node
        uses: ./.github/actions/setup-project

      - name: Lint and Unit Test
        uses: ./.github/actions/lint-and-unit-test

      - name: Build app
        run: npm run build
        env:
          VITE_AWS_MONITORING_API: ${{ secrets.AWS_MONITORING_API }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Terraform Apply
        uses: ./.github/actions/terraform-apply
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy images to AWS
        run: aws s3 sync public s3://web-apps-images-cdn

      - name: Invalidate images CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id E10X6DW9A9FH4P --paths "/*"

      - name: Deploy WebApp to AWS
        run: aws s3 sync dist s3://frontend-bootstrap-10

      - name: Invalidate WebApp CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id E1CKAPFXNJI750 --paths "/*"
